FROM node:18-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY frontend/ ./
RUN yarn install
RUN yarn build

FROM nginx:1.21.3 as production
WORKDIR /app
COPY --from=build /app/build ./
COPY nginx1.conf /etc/nginx/conf.d/default.conf
