version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile-front
      target: build
      context: .
    container_name: eval_dev
    command: yarn start
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    networks:
      - eval_dev_net
    depends_on:
      - nginx
#  backend:
#    build:
#      dockerfile: Dockerfile-back
#      context: .
#    container_name: backend_dev
#    command: python app.py
#    volumes:
#      - ./app.py:/app/app.py
#    ports:
#      - '5000:5000'
#    networks:
#      - eval_dev_net
#    depends_on:
#      - nginx
#  db:
#    image: redis:6.0.9
#    container_name: redis_dev
#    ports:
#      - '6379:6379'
#    networks:
#      - eval_dev_net
  nginx:
    image: nginx:1.22.0
    container_name: proxy_dev
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - eval_dev_net

networks:
  eval_dev_net:
    driver: bridge
